from gen import Tree

trees = [
Tree("root", 
     Tree("l"), 
     Tree("r")),

Tree("root", 
  Tree("l1", 
    Tree("l2", 
      Tree("l3", 
        Tree("l4")))),
  Tree("r1")),

Tree("root", 
  Tree("l1"),
  Tree("r1", 
    Tree("r2", 
      Tree("r3", 
        Tree("r4"))))
  ),

Tree("root", 
  Tree("l1", 
    Tree("l2", 
      Tree("l3"), Tree("l4"))),
  Tree("r1", 
    Tree("rl1"),
    Tree("rr1", 
      Tree("rr2"), Tree("rr3")))),

Tree("root", 
  Tree("l1", 
    Tree("l2", 
      Tree("l3", 
        Tree("l4", 
          Tree("l5"),
          Tree("l6")),
        Tree("l7")),
      Tree("l8")),
    Tree("l9")),
  Tree("r1", 
    Tree("r2", 
      Tree("r3"),
      Tree("r4")),
    Tree("r5"))),

Tree("root",
  Tree("l1",
    Tree("ll1"),
    Tree("lr1",
      Tree("lrl"),
      Tree("lrr"))),
  Tree("r1",
    Tree("rr2",
      Tree("rr3",
        Tree("rrl",
          Tree("rrll",
            Tree("rrlll"),
            Tree("rrllr")),
          Tree("rrlr"))))))
]
